# Generated by Django 6.0.5 on 2026-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_qr_code_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
    ]
