# Generated by Django 6.0.5 on 2026-05-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_payment_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_qr',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
    ]
